name: Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
      - '.github/**'
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
      
    - name: Restore the application
      run: nuget restore
      
    - name: Build for Windows
      run: dotnet publish Audio.Desktop -c Release -r win-x64 --self-contained true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: net7.0_windows
        path: Audio.Desktop/bin/Release/net7.0/win-x64/publish

  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
      
    - name: Restore the application
      run: nuget restore
      
    - name: Build for Linux
      run: dotnet publish Audio.Desktop -c Release -r linux-x64 --self-contained true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: net7.0_linux
        path: Audio.Desktop/bin/Release/net7.0/linux-x64/publish