name: Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
      - '.github/**'
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
      
    - name: Restore the application
      run: nuget restore
      
    - name: Build the application
      run: dotnet publish /t:Audio_Desktop /p:Configuration=Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: net7.0
        path: Audio.Desktop/bin/Release/net7.0/publish
